project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  agu-pdf: default


manuscript:
  notebooks:
    - notebook: notebooks/explore-busstops.qmd
      title: Exploring Bus Stop Data
