project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  agu-pdf: default


manuscript:
  notebooks:
    - notebook: notebooks/explore-bslocations.qmd
      title: Exploring Bus Stop Locations

    - notebook: notebooks/explore-busstops.qmd
      title: Exploring Origin - Destination Bus Stops Flows
      
    - notebook: notebooks/esda-busstops.qmd
      title: Exploratory Data Analysis for Bus Stop Locations 

